sudo: required
before_install:
  - sudo apt-get install build-essential
  - sudo apt-get install libfontconfig1
  - sudo apt-get install libqt5opengl5-dev
  - wget http://download.qt.io/official_releases/qt/5.7/5.7.0/qt-opensource-linux-x64-5.7.0.run
  - chmod +x qt-opensource-linux-x64-5.7.0.run
  - ./qt-opensource-linux-x64-5.7.0.run
  
language: cpp
compiler:
  - gcc
  
script:
  - cd ./MaxApplication
  - qmake
  - make
  - cd ../MaxUnitTest
  - qmake
  - make
  - ./MaxUnitTest/tst_maxunittest
